services:
  - type: web
    name: meu-site-flask
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    branch: main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: meu-banco-render
          property: connectionString
